[package]
name = "day_02"
version = "0.1.0"
authors = ["Philip Craig <689193+philipcraig@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
